Update autoclean

diff --git a/autoclean b/autoclean
--- a/autoclean
+++ b/autoclean
@@ -1,22 +1,91 @@
 #!/bin/bash
 
-# Checks if the number of arguments is correct
-if [ "$#" -ne 4 ]; then
-    echo "Usage: autoclean cachecln <value> ramtrig <value>"
+# Function to display usage message
+show_usage() {
+    echo "Usage: cachecln <value> ramtrig <value>"
+    echo "Example: cachecln 2 ramtrig 45"
     exit 1
-fi
+}
 
-# Arguments passed to the wrapper
-cachecln="$2"
-ramtrig="$4"
+# Detect Linux distribution
+detect_linux_distribution() {
+    if [[ -f /etc/redhat-release ]]; then
+        _release="centos"
+    elif grep -qiE "debian|ubuntu" /etc/issue; then
+        _release="debian"
+    elif grep -qiE "centos|red hat|redhat" /etc/issue; then
+        _release="centos"
+    elif grep -qiE "debian|ubuntu" /proc/version; then
+        _release="debian"
+    elif grep -qiE "centos|red hat|redhat" /proc/version; then
+        _release="centos"
+    else
+        echo -e "${RED}CentOS, Debian, or Ubuntu not detected. The script may not work correctly.${RESET}"
+        exit 1
+    fi
+}
+
+# Function to remove auto-clean script
+script_rm() {
+
+    if [[ $_release = centos ]]; then
+        service auto-clean.sh stop > /dev/null 2>&1
+        chkconfig --del auto-clean.sh > /dev/null 2>&1
+        rm -rf /etc/init.d/auto-clean.sh
+        pkill auto-clean.sh > /dev/null 2>&1
+    elif [[ $_release = debian ]] || [[ $_release = ubuntu ]]; then
+        update-rc.d -f auto-clean.sh remove > /dev/null 2>&1
+        rm -rf /etc/init.d/auto-clean.sh
+        pkill auto-clean.sh > /dev/null 2>&1
+    fi
+
+    rm -rf /usr/local/bin/*-auto
+    rm -rf /usr/local/bin/autoclean
+}
 
 # Path to the auto-clean.sh script
 script_path="/etc/init.d/auto-clean.sh"
 
-# Updates the parameters in the auto-clean.sh script
-sed -i "s/_cache_cln=.*/_cache_cln=$cachecln/" "$script_path"
-sed -i "s/_ram_trig=.*/_ram_trig=$ramtrig/" "$script_path"
+# Process the parameters
+while [ "$#" -gt 0 ]; do
+    case "$1" in
+        cachecln)
+            # Check if the second argument is a number between 1 and 3
+            if ! [[ "$2" =~ ^[1-3]$ ]]; then
+                echo "Invalid value for cachecln. It must be a number between 1 and 3."
+                show_usage
+            fi
+            sed -i "s/_cache_cln=.*/_cache_cln=$2/" "$script_path"
+            cache_cln="$2"
+            shift 2
+            ;;
+        ramtrig)
+            # Check if the second argument is a number between 5 and 90
+            if ! [[ "$2" =~ ^[5-9]|[1-8][0-9]|90$ ]]; then
+                echo "Invalid value for ramtrig. It must be a number between 5 and 90."
+                show_usage
+            fi
+            sed -i "s/_ram_trig=.*/_ram_trig=$2/" "$script_path"
+            ram_trig="$2"
+            shift 2
+            ;;
+        start)
+            /etc/init.d/auto-clean.sh
+            ;;
+        stop)
+            pkill auto-clean.sh > /dev/null 2>&1
+            ;;
+        remove)
+            script_rm
+            ;;
+        *)
+            show_usage
+            ;;
+    esac
+done
 
-# Starts the auto-clean.sh script
 pkill auto-clean.sh
-"$script_path"
+$script_path
+
+echo "cachecln: $cache_cln"
+echo "ramtrig: $ram_trig"
